Fix MacOS build (v2)
There is a missing header include that causes a build error depending
on the different ordering of the UnifedSources. And also fix this
warning/error from the compiler:

Source/WebKit/WebProcess/WebPage/WebPage.cpp:4100:39:
  error: temporary whose address is used as value of local variable 'nodeRespondingToClick'
  will be destroyed at the end of the full-expression [-Werror,-Wdangling]